package client.observer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import client.event.Event;
import client.event.Subject;
import logger.Logger;
import logger.LogLevel;

/**
 * Observables generate events of subjects that have been registered. Multiple subjects can be registered.
 * Observers can subscribe to events generated by Observables. Multiple Observers can subscribe to events generated.
 * An Observer can subscribe to multiple event subjects.
 * When an event is generated, the Observable notifies its subscribers.
 * 
 * TODO: reuse this code on both server and cliet
 */
public class Observable
{
    private Map<Subject, List<Observer>> registrar = new HashMap<Subject, List<Observer>>(); // listeners
    
    /**
     * Adds the subject specified to the list of event subjects generated by this Observable.
     * The Observable can start accepting subscriptions for the new subject.
     * 
     * @param subject the subject to be added to this Observale
     */
    public void registerSubject(Subject subject)
    {
        Logger.log(LogLevel.Debug, "Registering event subject: " + subject);
        registrar.putIfAbsent(subject, new ArrayList<Observer>());
    }
    
    /**
     * Removes the subject specified from the list of event subjects generated by this Observable.
     * The Observable stops accepting subscriptions for the subject removed and stops notifying Observers with the
     * subject removed.
     * All subscribers are removed for the event.
     * 
     * @param subject the subject to be unregistered
     */
    public void unregisterSubject(Subject subject)
    {
        Logger.log(LogLevel.Debug, "Unregistering event subject: " + subject);
        registrar.remove(subject);
    }
    
    /**
     * Subscribes observer to all events generated by the Observable.
     * 
     * @param observer the observer to be subscribed to events generated
     */
    public void subscribe(Observer observer)
    {
        for (Subject subject : registrar.keySet())
        {
            Logger.log(LogLevel.Debug, "New event listener subscription: " + subject);
            registrar.get(subject).add(observer);
        }
    }

    /**
     * Subscribes observer to events generated by the Observable.
     * Observer will only be notified of events with the subject specified.
     * 
     * @param subject  the subject the new observer is listening to
     * @param observer the observer that will listen to this Observable's events
     */
    public void subscribe(Subject subject, Observer observer)
    {
        Logger.log(LogLevel.Debug, "New event listener subscription: " + subject);
        if (registrar.containsKey(subject))
            registrar.get(subject).add(observer);
    }
    
    /**
     * Unsubscribes observer from all events generated by the Observable.
     * 
     * @param observer the observer to be unsubscribed from events generated
     */
    public void unsubscribe(Observer observer)
    {
        for (Subject subject : registrar.keySet())
        {
            Logger.log(LogLevel.Debug, "Event listener unsubscribed for " + subject);
            registrar.get(subject).remove(observer);
        }
    }
    
    /**
     * Unsubscribes observer from events of the subject specfied.
     * 
     * @param subject  the subject the observer is unsubscribing from
     * @param listener the observer unsubscribing
     */
    public void unsubscribe(Subject subject, Observer observer)
    {
        Logger.log(LogLevel.Debug, "Event listener unsubscribed for " + subject);
        if (registrar.containsKey(subject))
            registrar.get(subject).remove(observer);
    }

    /**
     * Notifies the event specified to all observers listening to this Observable's events.
     * 
     * @param event the event to be notified
     */
    public void notify(Event event)
    {
        Logger.log(LogLevel.Debug, "Notifying event listeners: \"" + event + "\"");
        if (registrar.containsKey(event.getSubject()))
        {
            for (Observer observer : registrar.get(event.getSubject()))
                observer.processEvent(event);
        }
    }
    
    /**
     * Notifies the event specified to the observer specified.
     * Only notifies observer if it has subscribed to the event's subject
     * 
     * @param observer the observer to be notified
     * @param event    the event to be notified
     */
    public void notify(Observer observer, Event event)
    {
        Logger.log(LogLevel.Debug, "Notifying event listener: \"" + event + "\"");
        if (registrar.containsKey(event.getSubject()))
            observer.processEvent(event);
    }
}
