package observer;

import java.util.ArrayList;
import java.util.List;

/**
 * Generates events and notifies its observers
 */
public class Observable<TEvent>
{
    private List<Observer<TEvent>> observers = new ArrayList<Observer<TEvent>>(); // list of observers

    /**
     * Subscribes the Observer specified to events generated by this Observable.
     * 
     * @param observer the observer that will listen to this Observable's events
     */
    public void subscribe(Observer<TEvent> observer)
    {
        observers.add(observer);
    }

    /**
     * Notifies the event specified to all observers listening to this Observable's events.
     * 
     * @param event the event to be notified
     */
    public void notify(TEvent event)
    {
        for (Observer<TEvent> observer : observers)
            observer.processEvent(event);
    }
}
