package event;

/**
 * Subjects of events generated by the game.
 */
public enum Subject
{
    ItemData,
    ItemCollected,
    MapData,
    PlayerConnected,
    PlayerDisconnected,
    PlayerUpdate,
    SendMessage,
    Unknown;
}
